name: Deploy to Pages
on:
  push:
    branches: [ main ] # nebo master, podle toho co používáš
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout
        with:
          submodules: recursive # Důležité pro načtení Duckquill
      - name: Build Zola
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: public
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
